import Container from 'react-bootstrap/Container';
import Col from 'react-bootstrap/Col';
import Head from 'next/head';
import Image from 'react-bootstrap/Image';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Row from 'react-bootstrap/Row';

const inter = Inter({ subsets: ['latin'] });

const Links = () => (
  <>
    <Link href="https://linkedin.com/in/jhcao" target="_blank">
      LinkedIn
    </Link>{' '}
    •{' '}
    <Link href="https://github.com/luig0/" target="_blank">
      GitHub
    </Link>{' '}
    •{' '}
    <Link href="https://twitter.com/jhcao" target="_blank">
      Twitter
    </Link>
  </>
);

const Content = () => (
  <>
    <p>
      Welcome to my website! I am a full stack software engineer with a passion for creating elegant, scalable, and
      user-friendly solutions to real-world problems.
    </p>

    <p>
      I hold both an MS Computer Science from the Georgia Institute of Technology as well as an MBA with a focus in
      Corporate Finance from Texas Christian University. In addition to my technical skills, I am a strong communicator
      and collaborator. I have worked on projects with cross-functional teams and stakeholders, and I understand the
      importance of clear and frequent communication to ensure the success of a project.{' '}
    </p>

    <p>
      I care deeply about writing high quality code that is performant, maintainable, and testable. I have honed my
      skills in a variety of technologies and frameworks, including JavaScript, Python, SQL, and Docker. I am
      comfortable working with both front-end and back-end technologies and have experience deploying applications to
      various cloud platforms.
    </p>

    <p>
      I am excited to continue learning and growing as a software engineer, and I am always eager to take on new
      challenges and opportunities. Thank you for taking the time to learn more about me, and I look forward to
      connecting with you!
    </p>
  </>
);

export default function Home() {
  return (
    <>
      <Head>
        <title>jhcao.net • About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Container className="content mt-5">
          <Row className="text-center mt-1 mb-3">
            <Col>
              <Links />
            </Col>
          </Row>
          <Row className="text-center pt-2 pb-1">
            <Col>
              <Image src="/headshot.png" alt="me" width={128} height={128} roundedCircle />
            </Col>
          </Row>
          <Row className="pt-1 mb-4">
            <Col>
              <div className="text-center fs-1 fw-bold">Johnathan Cao</div>
              <div className="text-center fs-6">
                Full stack software engineer with master's in computer science and 4 years professional experience
                building web applications.
              </div>
            </Col>
          </Row>
          <Row className="pt-2 pb-2 ps-1 pe-1 mb-5 with-bg rounded-4">
            <Col>
              <Content />
            </Col>
          </Row>
        </Container>
      </main>
    </>
  );
}
