import Container from 'react-bootstrap/Container';
import Col from 'react-bootstrap/Col';
import Head from 'next/head';
import Image from 'react-bootstrap/Image';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Row from 'react-bootstrap/Row';

const inter = Inter({ subsets: ['latin'] });

const Links = () => (
  <>
    <Link href="https://linkedin.com/in/jhcao" target="_blank">
      LinkedIn
    </Link>{' '}
    •{' '}
    <Link href="https://github.com/luig0/" target="_blank">
      GitHub
    </Link>{' '}
    •{' '}
    <Link href="https://twitter.com/jhcao" target="_blank">
      Twitter
    </Link>
  </>
);

const Content = () => (
  <>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
      magna aliqua. Feugiat pretium nibh ipsum consequat nisl vel. Pharetra sit amet aliquam id diam maecenas ultricies.
      Molestie a iaculis at erat. Sociis natoque penatibus et magnis dis. Sed sed risus pretium quam vulputate dignissim
      suspendisse in est. Sit amet luctus venenatis lectus. Adipiscing vitae proin sagittis nisl rhoncus mattis. Aliquam
      purus sit amet luctus venenatis lectus magna fringilla. In fermentum posuere urna nec tincidunt praesent semper
      feugiat nibh. Suscipit tellus mauris a diam maecenas. Tristique senectus et netus et malesuada fames ac. Lorem
      ipsum dolor sit amet consectetur adipiscing elit pellentesque. Lacus vel facilisis volutpat est. Euismod quis
      viverra nibh cras. A diam maecenas sed enim ut sem viverra aliquet eget.
    </p>

    <p>
      Arcu odio ut sem nulla. Magna etiam tempor orci eu lobortis elementum. Ac tortor vitae purus faucibus ornare
      suspendisse sed nisi lacus. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Cras tincidunt
      lobortis feugiat vivamus at augue eget arcu dictum. Venenatis lectus magna fringilla urna porttitor rhoncus dolor
      purus. Morbi non arcu risus quis varius quam quisque id diam. Sit amet venenatis urna cursus eget. Nibh nisl
      condimentum id venenatis a condimentum vitae sapien pellentesque. Elit scelerisque mauris pellentesque pulvinar
      pellentesque habitant morbi.
    </p>
  </>
);

export default function Home() {
  return (
    <>
      <Head>
        <title>jhcao.net • About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Container className="content mt-5">
          <Row className="text-center mt-1 mb-1">
            <Col>
              <Links />
            </Col>
          </Row>
          <Row className="text-center mt-3 mb-3">
            <Col>
              <Image src="/headshot.png" alt="me" width={128} height={128} roundedCircle />
            </Col>
          </Row>
          <Row className="text-center mt-1 mb-1 fs-1 fw-bold">
            <Col>Johnathan Cao</Col>
          </Row>
          <Row className="mt-3 mb-3">
            <Col>
              <Content />
            </Col>
          </Row>
        </Container>
      </main>
    </>
  );
}
